### ISSUE TITLE
streamlit link not working

### ISSUE THREAD

**Issue by bihari123** [annapurna1702/video_emotion_recognition#1]

**Comment by annapurna1702** [comment]
Hi ! Thank you for raising this issue. I see that the link, which was working earlier, has bumped into some technical issues.....I will check them and update as soon as possible.

**Comment by annapurna1702** [comment]
> _No description provided._

Hi ! **The issue has been solved...kindly check the link again**...also, please keep in mind that the application is still in test-stage, therefore some videos may not provide the exact emotion you're looking for... apologies in case of any such issue, and I promise that it will be solved soon.

**Comment by annapurna1702** [comment]
I am closing this issue here
